lb = float(input("enter weight in pounds:"))
kg = float(lb*0.4535)
print("weight in kg :", kg)
d = float(input("enter the amount in dollar : "))
rs = float(d*84.48)
print("amount in rupee : ",rs)
km = float(input("enter length in kilometer : "))
m = float(km*1000)
print("length in meter :",m)